import {readFile, writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import standalone from 'ajv/dist/standalone/index.js';
import {compile} from 'json-schema-to-typescript';
import {build} from 'esbuild';
// The schema is copied verbatim. Check its digest before generating either code or types.
const pins = JSON.parse(await readFile('vendor/PINS.json','utf8'));
for (const [file, hash] of Object.entries(pins.sha256)) {
  const actual = createHash('sha256').update(await readFile(`vendor/${file}`)).digest('hex');
  if (actual !== hash) throw new Error(`Pinned authority changed: ${file}`);
}
const schema = JSON.parse(await readFile('vendor/schema/open-ir-remote-v1.schema.json','utf8'));
const ajv = new Ajv2020({strict:false,allErrors:true,ownProperties:true,code:{source:true}});
// Ajv's date/time rules differ from the pinned Python helpers on years,
// separators, offsets and leap seconds. The record layer checks these formats
// against the authority's behaviour; keep URI validation compiled here.
addFormats(ajv, {mode:'full',formats:['uri']});
ajv.addFormat('date',true);
ajv.addFormat('date-time',true);
const validationCode=standalone(ajv,ajv.compile(schema));
// Resolve generated Ajv helper imports from this package, then bundle them into one browser file.
await build({stdin:{contents:validationCode,resolveDir:process.cwd()},bundle:true,platform:'browser',format:'esm',outfile:'src/schema-validator.js',minify:true});
await writeFile('src/record.ts', await compile({...schema,title:'OpenIrRecord'},'OpenIrRecord',{bannerComment:'/** Generated from the pinned Open IR v1 schema. Do not edit this file. */',additionalProperties:false,ignoreMinAndMaxItems:true}));
execFileSync(process.execPath,['node_modules/typescript/bin/tsc'],{stdio:'inherit'});
await build({entryPoints:['src/index.ts'],bundle:true,minify:true,platform:'browser',format:'esm',outfile:'dist/browser.js'});
await build({entryPoints:['src/irdb.ts'],bundle:true,minify:true,platform:'browser',format:'esm',outfile:'dist/irdb.browser.js'});
